Implemented Github Actions
rajsandhu/group-2-App-Infra pull request #1
Opened 2022-10-31 13:40 UTC by p-calvino

The Github Actions has been implemented. The test (terraform init and plan) was successful on pushing on branch. In order to test the terraform apply on main branch we need to merge this branch to the main one.

2022-10-31 14:22 UTC, ash-ley requested changes
I recommend these improvements:

- Having a separate backend key for each repo (looks like you have noticed this already :) )
- Remove main.tf and role.tf (these should be inside group-2-Backend repo only as you want to manage your terraform separately with different backends)
- Consider adding a terraform validate task to your workflows before terraform plan is run

2022-10-31 14:59 UTC, p-calvino commented
@ash-ley thanks for the suggestions. Now it should be fine (I think) :)

2022-10-31 15:38 UTC, ash-ley approved these changes

2022-11-01 09:51 UTC, isabellemsan approved these changes

2022-11-01 11:19 UTC, mikomeller approved these changes
thank you Paolo

2022-11-01 16:04 UTC, merged